#!/bin/sh
. ${0%/*}/symfony-projects.inc.sh

GREPEXTOPT=""
FINDMETHOD="-iname"
while getopts "Eir" opt; do
case $opt in
  E) GREPEXTOPT="${GREPEXTOPT}E";;
  i) GREPEXTOPT="${GREPEXTOPT}i";;
  r) FINDMETHOD="-iregex";;
esac
done
shift $(( $OPTIND - 1))

GREPFOR="$1"
if [ -n "$2" ]; then
	FINDWHAT="$2"
fi

if [ -n "$FINDWHAT" ]; then
	# user specified filename wildcard or full-path regexp
	GREPOPT="--color=always -Hn${GREPEXTOPT}"
	return find . -type f $FINDMETHOD "$FINDWHAT" | \
		xargs grep "$GREPOPT" "$GREPFOR"
elif [ -n "$GREPFOR" ]; then
	# user is only grepping for the text
	GREPOPT="--color=always -rHn${GREPEXTOPT}"
	return grep "$GREPOPT" "$GREPFOR" .
fi


echo "usage: $0 [-Eir] <grep text> [filename wildcard / full-path regexp]"
echo ""
echo "  options:"
echo "    -E      grep's -E (extended regexp)"
echo "    -i      grep's -i (case-insensitive)"
echo "    -r      find's -iregex (case-insensitive full-path regexp)"
echo "            defaults to -iname (case-insensitive filename wildcards)"
echo ""
