#!/bin/sh
OLD_PWD=$PWD
NEW_PWD=`echo $PWD | sed -r "s;($HOME)(/sites/)([^/]+)(.*);\1\2\3;"`

GREPEXTOPT=""
while getopts "Ei" opt; do
	case $opt in
		E) GREPEXTOPT="${GREPEXTOPT}E";;
		i) GREPEXTOPT="${GREPEXTOPT}i";;
		*) echo "usage: $0 [options] <grep text> [file path regex]";;
	esac
done

if [ -z "$GREPEXTOPT" ]; then
	# sfg <grep text> [path regex]
	GREPTEXT="$1"
	if [ -n "$2" ]; then
		GREPREGEX="$2"
	fi
else
	# sfg <options> <grep text> [path regex]
	GREPTEXT="$2"
	if [ -n "$3" ]; then
		GREPREGEX="$3"
	fi
fi


cd $NEW_PWD
if [ -n "$GREPREGEX" ]; then
	# user specified file/path regex
	GREPOPT="-Hn${GREPEXTOPT}"
	find . -type f -iname "$GREPREGEX" | xargs grep --color=always "$GREPOPT" "$GREPTEXT"
elif [ -n "$GREPTEXT" ]; then
	# user is only grepping for the text
	GREPOPT="-rHn${GREPEXTOPT}"
	grep "$GREPOPT" --color=always ""$GREPTEXT"" .
else
	echo "usage: $0 [<options>] <grep text> [<file path regex>]"
fi
cd $OLD_PWD

